import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Provider } from "./dashboard/_components/Provider";
import dynamic from "next/dynamic";
import { cookies } from "next/headers";

const inter = Outfit({ subsets: ["latin"] });

const AppThemeProvider = dynamic(
  () => import("@/app/dashboard/_components/context/theme"),
  {
    ssr: false,
  }
);

export const metadata: Metadata = {
  title: "Gemini Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClerkProvider>
          <AppThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
          >
            {children}
          </AppThemeProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
